// This file contains all pixel art assets for the game as Base64-encoded Data URLs.
// This removes the need for external image files.

export const PIXEL_ASSETS = {
    // --- Game World Sprites ---
    settler: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADlJREFUOI1jZGBgEGHAD97/M/j//z/D2MDw/x+aYmBgyKEPFP4zSAxIMjAxovgPkv8g8yMFAGmAB2mrRz1QAAAAAElFTkSuQmCC',
    child: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACdJREFUOI1jZGBgEGHAD97/M/j//z/D2MDw/x+aYmBgyKEPAgBKRwB2eS6XsgAAAABJRU5ErkJggg==',
    tree: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAHlJREFUOI2N07ENwDAIBMAjRICFGMQCjMBSjMAoDRwP9/YkFa2NaB/5d7snZ4aZgYGBgRGaa6bT09PzHyT/A/lfJH8D+V8k/wT5byssFCS3w0sVlE5yG19QKk3ubrygVJrcDR8oTZO4m26gVErnD3ZALfQBkZ4A96EgN10AAAAASUVORK5CYII=',
    stone: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAGFJREFUOI3F0LENgDAIBNAbQUE9VEM9VEM9VEM91MMg2ZPDpEwu6J/kkrszMTAwMDAi8M80WwDBs/9E8mch/wlkvxByL5LdKeyfENkzpF4S+Sfkdkj9htRHcvsh9QGzGgC8v2g6TQAAAABJRU5ErkJggg==',
    berryBush: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAGdJREFUOI3t0rENgCAMAFHbIKzCKqzCKqwOmzZt2oYxMYRImj+k+3PyAwMD8y8mjy8A8H/xV4C8pNCr+Csg7yn0Kn4JyDtKXQv/gnARUpfCv+CcB9Sh8F/49wHtKn4LgL5E9g040QCc4k4pRgAAAABJRU5ErkJggg==',
    sapling: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADxJREFUOI1jZGBgEGHAD97/M/j//z/DyMjAPwYjIyODIUc/MPwvAwPDKyMjwyuC/wL/Z/A/BwYG/v8AMV0B54rIoW0AAAAASUVORK5CYII=',
    wood_pile: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADtJREFUOI1jZGBg+M/AwCDAwMDAsIsLC/8zoKCg+M/AwAAyMv5nAAkGpv//Z2BgYPhPwMQQoUAAANcgCqXjO2lJAAAAAElFTkSuQmCC',
    stone_pile: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAExJREFUOI3t0aENACAMwDDv6C7qLrqLu84KCIH+0sKLfEhyYmBgYPhv5Ps+APg3gZ8BfAWEr0L4KyCvheCvIK+F4q9A3Bfi3wL48zE9AazYTNujAAAAAElFTkSuQmCC',
    food_pile: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAEFJREFUOI1jZGBg+M/AwCDAwMDAsAICAv8zSEhI+M/AwAAyMv5nAAkGpv//Z2BgYPhPwMQQoUAAALZ8EHVj9PtaAAAAAElFTkSuQmCC',
    hut: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAHBJREFUOI1jZGBg+M/AwCDAwMDAsIsLC/8zKCgo/mdgYGBgYWBg+E/BwMDw/3+GHQwDQw4wMPynYmBg+M/AwAgGBgYGRoYPhv//MwwNTQwM/xnYGBgZGBgY/jPwc4hoYGBgYGFg4P8/AwMARhAW1nJ2Xk8AAAAASUVORK5CYII=',
    stockpile: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAEhJREFUOI1jZGBg+M/AwCDAwMDAsIsLC/8zoKCg+M/AwAAyMv5nAAkGpv//Z2BgYPhPwMQQoUAYGBgYWBgY/jPwc4hoYGCAgYGBgQEA+qELK44yL6QAAAAASUVORK5CYII=',
    mine: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAE5JREFUOI3t0rENgCAMAFG7sAqr8I9VYR22bt26DYRIEJJkPyj3c/IDAwPzL+YN7gDAf+NfAfJW+Ff8FRAfIX0L/4KwEVKXwr9g3AfUofBf+PcB7Sp+C8B4NBVn6wFqT71L2QAAAABJRU5ErkJggg==',
    farm: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAGVJREFUOI3tkrENgCAMBDvRqNVoNGq1msnoVJoYmAhhkh/9kO7H5QcGBubfjD++AOA/8VeA/D+hV/FXQPK/hV7Fr4D8P6FXYRSE/xdaFYgD8v+FXgVjCP9eaFYgHsh/CwB8PBMn6wG/pKQv8gAAAABJRU5ErkJggg==',
    foresterLodge: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAFlJREFUOI1jZGBg+M/AwCDAwMDAsIsLC/8zKCgo/mdgYGBgYWBg+E/BwMDw/3+GHQwDQw4wMPwnYgCkfzIywAAyMDD8Z2RgYMjQxMDwn4mBgYEBAJ1kE4m0mBYvAAAAAElFTkSuQmCC',
    wood_carry: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACVJREFUOI1jZGBg+M/AwCDAwMDAsIsLC/8zKCgo/mdgYGAABwDPtgf/Vd3hAAAAAElFTkSuQmCC',
    stone_carry: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACRJREFUOI1jZGBg+M/AwCDAwMDAsH///v2fAQYGBgYcAADs4wf/2k5zGAAAAABJRU5ErkJggg==',
    food_carry: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACRJREFUOI1jZGBg+M/AwCDAwMDAsAICAv8zSEhI+M/AwAAHAACl0wf/P4a/tQAAAABJRU5ErkJggg==',

    // --- UI Icons ---
    wood: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACVJREFUOI1jZGBg+M/AwCDAwMDAsIsLC/8zKCgo/mdgYGAABwDPtgf/Vd3hAAAAAElFTkSuQmCC',
    stone: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACRJREFUOI1jZGBg+M/AwCDAwMDAsH///v2fAQYGBgYcAADs4wf/2k5zGAAAAABJRU5ErkJggg==',
    food: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACRJREFUOI1jZGBg+M/AwCDAwMDAsAICAv8zSEhI+M/AwAAHAACl0wf/P4a/tQAAAABJRU5ErkJggg==',
    day: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADhJREFUOI1jZGBg+M/AwCDAwMDAsAICAv+B6gEkGxj+M/D/P8MMg4FBA5pB4T8Dk1I0PzEFAAChqBCvOLjTFAAAAABJRU5ErkJggg==',
    time: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADJJREFUOI1jZGBg+M/AwCDAwMDAsH///v2fQUIiYGBgYPgPwYT/DIwMDBxgcUPT/8yaAFUAL70Ta+Uo4pgAAAAASUVORK5CYII=',
    idle: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADxJREFUOI1jZGBgEGHADx47doyF/zP8//9/hrGB4f8/NMXAwJBDHydg+P+fgUkhmh+Z/yDxPxKLEgMA33UTa0o9L50AAAAASUVORK5CYII=',
    builder: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAD9JREFUOI1jZGBg+M/AwCDAwMDAsGzZsn+gYgDJBsZ/Bv//Z5hBGFjQAFkQ/mdgUqL5idSQLADxPxKLEgMAJkQVa8v5iJAAAAAASUVORK5CYII=',
    lumberjack: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAFFJREFUOI1jZGBg+M/AwCDAwMDAsG/fvgMMDAwMDAwM/xlA8s+QBmYGBoYPhv//M/g/A8XBjA0M/xlYGFQeMPvB/w9k/E/EAGQAEgAu2xZropJjxgAAAABJRU5ErkJggg==',
    gatherer: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAEFJREFUOI1jZGBg+M/AwCDAwMDAsBoA8v9/hhiYgQGagYFhA8P//wz/DExyMGAgH8j4n4gByAAkAEKeGmnlMBoOAAAAAElFTkSuQmCC',
    miner: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAEVJREFUOI1jZGBg+M/AwCDAwMDAsGfPHgMDAwPD/v//M4wZGBgY/jMwMvg/g4TBgIF8QMY/MR+QAUgAIkAUa0s/1wUAAAAASUVORK5CYII=',
    farmer: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAElJREFUOI1jZGBg+M/AwCDAwMDAsBqA5P8/QwxYQClgYGBgYGBg+M/AwCDD/38GNoIpAwP/MzAxyMEAHcgY/zSgA5AASAD8lRVryrU9HwAAAABJRU5ErkJggg==',
    forester: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADhJREFUOI1jZGBg+M/AwCDAwMDAsG/fvgMMDAwMDAwM/xlA8s+QBmYGBoYPhv//M/g/A8XBjA0MAQDmPRNrPihzHwAAAABJRU5ErkJggg==',
    pause: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAABdJREFUOI1jZGBg+M/AwCDAwMDAcGfOnAEEAEN4BAuA33pLAAAAAElFTkSuQmCC',
    play: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACBJREFUOI1jZGBg+M/AwCDAwMDAcGfOnAEkGxj+M2AAAKZ7Ewtx2sKeAAAAAElFTkSuQmCC',
    ff2: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAACtJREFUOI1jZGBg+M/AwCDAwMDAcGfOnAEkGxj+M2CIUQDJBsZ/BgwA2isVC8w8/AgAAAAASUVORK5CYII=',
    ff4: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADBJREFUOI1jZGBg+M/AwCDAwMDAcGfOnAEkGxj+M2CIUQDJBsZ/BgyxCyAZgAQA9tUXC5/RzQ4AAAAASUVORK5CYII=',
};
